/**
 * `/@name/wantlist` — records a member means to hear.
 *
 * ============================================================================
 * THE PRIVACY CHECK IS DUPLICATED IN `generateMetadata` AND IN THE PAGE BODY (I-15, SEC-02).
 *
 * TWO ENTRY POINTS INTO ONE ROUTE, AND THE SOURCE HAD THE CHECK ON ONLY ONE OF THEM. In the
 * television original the equivalent route's BODY 404'd while the `<title>` and
 * `<meta name="description">` of every private collection still rendered — which made the
 * contents enumerable anonymously by reading nothing but the document head. Metadata is
 * generated by a separate function call, so it inherits nothing from the body's guard.
 *
 * Worse here: the original has NO PRIVACY FLAG ON THIS SURFACE AT ALL, so `/@anyone/watchlist`
 * is fully public to a signed-out visitor. `users.wantlist_private` is the fix, and
 * `canViewWantlist` is the whole rule in one pure function precisely so that it can be called
 * twice without the two copies drifting.
 *
 * ANY NEW ENTRY POINT NEEDS THE SAME CALL — an OpenGraph image route (`opengraph-image.tsx`),
 * an RSS or JSON feed, an API handler, a sitemap entry, a `route.ts` under this folder. Each
 * of those is a separate function that Next calls independently, so each is a separate place
 * for the rule to be missing. The rule is `canViewWantlist(member, viewer?.id)` and the
 * `viewerId` must come from the SESSION, never from a route parameter or a form field.
 * ============================================================================
 *
 * `notFound()` RATHER THAN A 403. A 403 confirms that the queue exists and that the member has
 * one, which is the fact being protected; a 404 is indistinguishable from a mistyped handle.
 * It is also the same answer `ProfileTabs` is told to expect — the tab is dropped for a
 * visitor who cannot see this page, because a tab that leads to a 404 is worse than an absent
 * one.
 */

import type { Metadata } from "next";
import { Disc3 } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { loadProfile } from "@/app/[username]/layout";
import { Button } from "@/components/ui/button";
import { Badge, EmptyState, SectionHeading } from "@/components/ui/primitives";
import { currentUser } from "@/lib/auth/session";
import { canViewWantlist, getWantlist } from "@/lib/db/queries/users";
import { formatDate, plural, releaseYear } from "@/lib/format";
import { albumCover } from "@/lib/providers/images";
import { albumSlug, artistSlug } from "@/lib/slug";

/** 64px rendered (`size-16`), requested at the 250px rung so it is sharp on a 2x screen. */
const THUMB_SOURCE_WIDTH = 250;

type PageProps = { params: Promise<{ username: string }> };

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { username } = await params;
  const [member, viewer] = await Promise.all([loadProfile(username), currentUser()]);

  // ENTRY POINT 1 OF 2. See the module docblock: the body's copy of this check does not cover
  // this function, and the leak the original shipped was exactly this call being absent.
  if (!canViewWantlist(member, viewer?.id)) notFound();

  const name = member.displayName ?? member.username;

  return {
    title: `${name}'s wantlist`,
    description: `Records ${name} is planning to hear.`,
  };
}

export default async function WantlistPage({ params }: PageProps) {
  const { username } = await params;
  const [member, viewer] = await Promise.all([loadProfile(username), currentUser()]);

  // ENTRY POINT 2 OF 2. Independently evaluated, deliberately not shared with the metadata
  // function — there is no way to share it, which is the whole shape of this defect class.
  if (!canViewWantlist(member, viewer?.id)) notFound();

  const isOwner = viewer?.id === member.id;
  const name = member.displayName ?? member.username;
  const entries = await getWantlist(member.id);

  return (
    <div className="space-y-6">
      <SectionHeading
        eyebrow="Wantlist"
        title={`${name} wants to hear`}
        as="h1"
        action={
          /*
           * THE PRIVATE BADGE IS SHOWN TO THE OWNER ONLY, and it can only ever BE the owner:
           * a private queue 404s above for everybody else, so this branch is unreachable for a
           * visitor. It is still written as `isOwner &&` rather than relying on that, because
           * a badge reading "Private" is the kind of thing that must not become visible if the
           * gate above is ever loosened.
           */
          isOwner && member.wantlistPrivate ? <Badge tone="amber">Private</Badge> : null
        }
      />

      <p className="font-mono text-[0.6875rem] uppercase tracking-wider tabular text-faint">
        {plural(entries.length, "record")}
      </p>

      {entries.length === 0 ? (
        <EmptyState
          title={isOwner ? "Nothing queued" : `${name}'s wantlist is empty`}
          description={
            isOwner
              ? "Add a record from its own page and it waits here until you play it. A note is optional — it is for why you wanted it."
              : "Records appear here as they are added."
          }
          action={
            isOwner ? (
              <Button asChild variant="primary">
                <Link href="/albums">Browse albums</Link>
              </Button>
            ) : null
          }
        />
      ) : (
        /*
          ROWS, NOT A COVER GRID, and the note is the reason. A wantlist entry carries up to 280
          characters of "why I wanted this", which a 132px caption cannot hold — and a queue is
          read top to bottom rather than scanned as artwork. `divide-y` gives the hairline
          between rows without a border on the first.
        */
        <ul className="divide-y divide-line">
          {entries.map((entry) => {
            const href = `/album/${albumSlug(entry.album.title, entry.album.id)}`;
            const cover = albumCover(
              { coverPath: entry.album.coverPath, mbid: entry.album.mbid },
              THUMB_SOURCE_WIDTH,
            );
            const year = releaseYear(entry.album.releaseDate);
            const added = formatDate(entry.addedAt);

            return (
              <li key={entry.album.id} className="flex items-start gap-4 py-4">
                {/*
                  The wrapping link is the `group`, which is what drives `.sleeve`'s hover lift.
                  `aria-hidden` plus `tabIndex={-1}`: the title link below is the same
                  destination, and two tab stops to one album is one too many.
                */}
                <Link href={href} className="group w-16 shrink-0" tabIndex={-1} aria-hidden="true">
                  <div className="sleeve">
                    {cover ? (
                      <img
                        src={cover}
                        alt=""
                        loading="lazy"
                        decoding="async"
                        className="size-full object-cover"
                      />
                    ) : (
                      <div className="flex size-full items-center justify-center">
                        <Disc3 className="size-6 text-line-bright" aria-hidden="true" />
                      </div>
                    )}
                  </div>
                </Link>

                <div className="min-w-0 flex-1">
                  <p className="text-sm">
                    <Link href={href} className="text-paper transition-colors hover:text-amber">
                      {entry.album.title}
                    </Link>
                  </p>
                  <p className="mt-0.5 truncate font-mono text-[0.6875rem] tabular text-faint">
                    <Link
                      href={`/artist/${artistSlug(entry.artist.name, entry.artist.id)}`}
                      className="transition-colors hover:text-paper"
                    >
                      {entry.artist.name}
                    </Link>
                    {year ? ` · ${year}` : ""}
                  </p>
                  {entry.note ? (
                    // `whitespace-pre-line` and escaped children: there is no markdown renderer
                    // in this application and `dangerouslySetInnerHTML` is never the answer.
                    <p className="mt-2 whitespace-pre-line text-[0.8125rem] leading-relaxed text-muted">
                      {entry.note}
                    </p>
                  ) : null}
                </div>

                {added ? (
                  <p className="shrink-0 font-mono text-[0.6875rem] tabular text-faint">
                    <span className="sr-only">Added </span>
                    {added}
                  </p>
                ) : null}
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
